language: go

go:
- 1.12.x

env:
  - DEP_VERSION=0.5.1

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - dep ensure -v --vendor-only

